name: "Build Capture Engine"
description: "Builds Qt native and Rust wrapper for Capture Engine"
inputs:
  target:
    description: "Rust target triple"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    # --- Linux (Docker) ---
    - name: Build Linux Artifacts (Docker)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        docker build -t spatial-builder -f sidecars/qt-capture/Dockerfile .
        # Build both Qt and Rust wrapper inside Docker
        docker run --rm -v $PWD:/build -w /build spatial-builder bash -c "cargo xtask build-capture-qt && cargo build --release -p capture-engine"

    # --- macOS ---
    - name: Install Qt (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        brew install qt@6
        echo "Qt6_DIR=$(brew --prefix qt@6)" >> $GITHUB_ENV

    # --- Windows ---
    - name: Install Qt (Windows)
      if: runner.os == 'Windows'
      uses: jurplel/install-qt-action@v4
      with:
        version: "6.6.0"
        host: "windows"
        target: "desktop"
        arch: "win64_msvc2019_64"
        cached: true

    - name: Setup MSVC (Windows)
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1

    # --- Native Build (Non-Linux) ---
    - name: Build Qt Native (Unix - No Docker)
      if: runner.os == 'macOS'
      shell: bash
      run: cargo xtask build-capture-qt

    - name: Build Qt Native (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: cargo xtask build-capture-qt

    - name: Build Rust Wrapper (Unix)
      if: runner.os != 'Windows' && runner.os != 'Linux'
      shell: bash
      run: cargo build --release -p capture-engine

    - name: Build Rust Wrapper (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: cargo build --release -p capture-engine
